apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dsm
resources:
  - namespace.yaml
  - postgres.yaml
  - backend.yaml
  - ingress.yaml
images:
  - name: ghcr.io/jumarubea/dsm-api
    newTag: sha-aa1e8b18a8a5e75b6b77de50c4478cc34f771cf6
