apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dsm
resources:
  - namespace.yaml
  - postgres.yaml
  - backend.yaml
  - ingress.yaml
images:
  - name: ghcr.io/jumarubea/dsm-api
    newTag: sha-9a5cefc1843e1c12b630a6e073c884500700e09a
