apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dsm
resources:
  - namespace.yaml
  - postgres.yaml
  - backend.yaml
  - ingress.yaml
images:
  - name: ghcr.io/jumarubea/dsm-api
    newTag: sha-cb518cab3d2814058963f7fd6398f5a932ee0511
