export const serializeSale = (sale, items = [], payments = []) => ({
  id: sale.id,
  type: sale.type,
  status: sale.status,
  customer_id: sale.customer_id,
  served_by: sale.served_by,
  delivery_address: sale.delivery_address,
  expected_delivery_at: sale.expected_delivery_at,
  subtotal: sale.subtotal,
  total: sale.total,
  payment_method: sale.payment_method,
  payment_status: sale.payment_status,
  void_reason: sale.void_reason,
  created_at: sale.created_at,
  items: items.map((i) => ({
    id: i.id,
    product_id: i.product_id,
    quantity: i.quantity,
    unit_price: i.unit_price,
    line_total: i.line_total,
  })),
  payments: payments.map((p) => ({
    id: p.id,
    method: p.method,
    amount: p.amount,
    status: p.status,
    reference: p.reference,
    created_at: p.created_at,
  })),
});
